/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRANSACTION_H_RPCGEN
#define _TRANSACTION_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct transaction_t {
	int to;
	int from;
	int account;
	double value;
};
typedef struct transaction_t transaction_t;
#ifdef __cplusplus
extern "C" bool_t xdr_transaction_t(XDR *, transaction_t*);
#elif __STDC__
extern  bool_t xdr_transaction_t(XDR *, transaction_t*);
#else /* Old Style C */
bool_t xdr_transaction_t();
#endif /* Old Style C */


struct result_t {
	double value;
	int success;
	struct {
		u_int msg_len;
		char *msg_val;
	} msg;
};
typedef struct result_t result_t;
#ifdef __cplusplus
extern "C" bool_t xdr_result_t(XDR *, result_t*);
#elif __STDC__
extern  bool_t xdr_result_t(XDR *, result_t*);
#else /* Old Style C */
bool_t xdr_result_t();
#endif /* Old Style C */


#define TRANSACTION ((rpc_uint)10101)
#define TVERS ((rpc_uint)1)

#ifdef __cplusplus
#define TRANSFER ((rpc_uint)1)
extern "C" result_t * transfer_1(transaction_t *, CLIENT *);
extern "C" result_t * transfer_1_svc(transaction_t *, struct svc_req *);
#define DEPOSIT ((rpc_uint)2)
extern "C" result_t * deposit_1(transaction_t *, CLIENT *);
extern "C" result_t * deposit_1_svc(transaction_t *, struct svc_req *);
#define WITHDRAW ((rpc_uint)3)
extern "C" result_t * withdraw_1(transaction_t *, CLIENT *);
extern "C" result_t * withdraw_1_svc(transaction_t *, struct svc_req *);
#define INQUIRY ((rpc_uint)4)
extern "C" result_t * inquiry_1(transaction_t *, CLIENT *);
extern "C" result_t * inquiry_1_svc(transaction_t *, struct svc_req *);
#define STARTSESSION ((rpc_uint)5)
extern "C" result_t * startsession_1(void *, CLIENT *);
extern "C" result_t * startsession_1_svc(void *, struct svc_req *);
#define STOPSESSION ((rpc_uint)6)
extern "C" result_t * stopsession_1(void *, CLIENT *);
extern "C" result_t * stopsession_1_svc(void *, struct svc_req *);

#elif __STDC__
#define TRANSFER ((rpc_uint)1)
extern  result_t * transfer_1(transaction_t *, CLIENT *);
extern  result_t * transfer_1_svc(transaction_t *, struct svc_req *);
#define DEPOSIT ((rpc_uint)2)
extern  result_t * deposit_1(transaction_t *, CLIENT *);
extern  result_t * deposit_1_svc(transaction_t *, struct svc_req *);
#define WITHDRAW ((rpc_uint)3)
extern  result_t * withdraw_1(transaction_t *, CLIENT *);
extern  result_t * withdraw_1_svc(transaction_t *, struct svc_req *);
#define INQUIRY ((rpc_uint)4)
extern  result_t * inquiry_1(transaction_t *, CLIENT *);
extern  result_t * inquiry_1_svc(transaction_t *, struct svc_req *);
#define STARTSESSION ((rpc_uint)5)
extern  result_t * startsession_1(void *, CLIENT *);
extern  result_t * startsession_1_svc(void *, struct svc_req *);
#define STOPSESSION ((rpc_uint)6)
extern  result_t * stopsession_1(void *, CLIENT *);
extern  result_t * stopsession_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define TRANSFER ((rpc_uint)1)
extern  result_t * transfer_1();
extern  result_t * transfer_1_svc();
#define DEPOSIT ((rpc_uint)2)
extern  result_t * deposit_1();
extern  result_t * deposit_1_svc();
#define WITHDRAW ((rpc_uint)3)
extern  result_t * withdraw_1();
extern  result_t * withdraw_1_svc();
#define INQUIRY ((rpc_uint)4)
extern  result_t * inquiry_1();
extern  result_t * inquiry_1_svc();
#define STARTSESSION ((rpc_uint)5)
extern  result_t * startsession_1();
extern  result_t * startsession_1_svc();
#define STOPSESSION ((rpc_uint)6)
extern  result_t * stopsession_1();
extern  result_t * stopsession_1_svc();
#endif /* Old Style C */

#endif /* !_TRANSACTION_H_RPCGEN */
