/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "transaction.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

result_t *
transfer_1(argp, clnt)
	transaction_t *argp;
	CLIENT *clnt;
{
	static result_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, TRANSFER, xdr_transaction_t, argp, xdr_result_t, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

result_t *
deposit_1(argp, clnt)
	transaction_t *argp;
	CLIENT *clnt;
{
	static result_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DEPOSIT, xdr_transaction_t, argp, xdr_result_t, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

result_t *
withdraw_1(argp, clnt)
	transaction_t *argp;
	CLIENT *clnt;
{
	static result_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, WITHDRAW, xdr_transaction_t, argp, xdr_result_t, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

result_t *
inquiry_1(argp, clnt)
	transaction_t *argp;
	CLIENT *clnt;
{
	static result_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, INQUIRY, xdr_transaction_t, argp, xdr_result_t, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

result_t *
startsession_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static result_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, STARTSESSION, xdr_void, argp, xdr_result_t, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

result_t *
stopsession_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static result_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, STOPSESSION, xdr_void, argp, xdr_result_t, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
